apiVersion: stunner.l7mp.io/v1alpha2
kind: GatewayConfig
metadata:
  name: stunner-gatewayconfig
  namespace: default
spec:
  realm: stunner.l7mp.io
  authType: plaintext
  userName: "user-1"
  password: "pass-1"
